#### Question 1.	Python program to add two Matrices

In [3]:
import numpy as np

a = np.array([1,3,5,7,4])
b = np.array([5,7,3,2,6])

print(a+b)

[ 6 10  8  9 10]


#### Question 2.	Python program to multiply two matrices

In [4]:
a = np.array([1,3,5,7,4])
b = np.array([5,7,3,2,6])

print(a*b)

[ 5 21 15 14 24]


#### Question 3.	Python program for Matrix Product

In [6]:
a = np.array([[1,3,5,7,4],[1,2,3,5,6]])
b = np.array([[5],[7],[3],[2],[6]])

print(np.dot(a,b))

[[79]
 [74]]


#### Question 4. Adding and Subtracting Matrices in Python

In [7]:
a = np.array([1,3,5,7,4])

# Adding 5
print(a+5)

# Subtracting 3
print(a-3)

[ 6  8 10 12  9]
[-2  0  2  4  1]


#### Question 5.	Transpose a matrix in Single line in Python

In [12]:
a = np.array([[5,7],[3,2],[6,4]])

print('Before traspose:')
print(a)
print('After transpose:')
print(np.transpose(a))  # can also use a.T to transpose

Before traspose:
[[5 7]
 [3 2]
 [6 4]]
After transpose:
[[5 3 6]
 [7 2 4]]


#### Question 6.	Python | Matrix creation of n*n

In [28]:
n = int(input('Enter value of n: '))

matrix = np.array([list(range(n*i+1, (n*(i+1)+1))) for i in range(n)])
print(matrix)

Enter value of n: 5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


#### Question 7.	Python | Get Kth Column of Matrix

In [34]:
matrix = [[3,4,5],[5,6,7],[7,8,9]]
k=1

print([x[k] for x in matrix])

[4, 6, 8]


#### Question 8.	Python – Vertical Concatenation in Matrix

In [40]:
a = ['sun', 'moon', 'star']
b = ['day', 'light', 'struck']

print([''.join(ele) for ele in zip(a,b)])

['sunday', 'moonlight', 'starstruck']


#### Question 9.	Python program to check if a string is palindrome or not

In [42]:
my_string = input('Enter a string : ')

print('Palindrome' if my_string == my_string[::-1] else 'Not Palindrome')

Enter a string : MALAYALAM
Palindrome


#### Question 10.	Python program to check whether the string is Symmetrical or Palindrome

In [49]:
my_string = input('Enter a string : ')
mid = round(len(my_string)/2)

print('Symmetrical' if my_string[0:mid] == my_string[mid:] else 'Not Symmetrical')
print('Palindrome' if my_string == my_string[::-1] else 'Not Palindrome')

Enter a string : amaama
Symmetrical
Palindrome
